ervices:
  db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    env_file: .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

